version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Admin123*
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - db
volumes:
  dbdata:
