version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: Admin123*
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    volumes:
      - dbdata:/var/opt/mssql
  api:
    build:
      context: ./Backend
      dockerfile: TalentQuest.API/Dockerfile
    ports:
      - 8083:80
      - 443:443
    depends_on:
      - db
  frontend:
    build:
      context: ./TalentQuest.UI
      dockerfile: Dockerfile
    ports:
      - 4200:80       
volumes:
  dbdata:
